name: CI/CD

on:
  push:
    branches: [ main ]

jobs:

  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin \
          547619294594.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Image
        run: |
          docker build --no-cache -t plant_diseases_detector:${{ github.sha }} .

      - name: Tag Image
        run: |
          docker tag plant_diseases_detector:${{ github.sha }} \
          547619294594.dkr.ecr.eu-north-1.amazonaws.com/plant_diseases_detector:${{ github.sha }} 
          

      - name: Push Image
        run: |
          docker push \
          547619294594.dkr.ecr.eu-north-1.amazonaws.com/plant_diseases_detector:${{ github.sha }}

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted   # Your EC2 runner

    steps:
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin \
          547619294594.dkr.ecr.eu-north-1.amazonaws.com

      - name: Pull Latest Image
        run: |
          docker pull \
          547619294594.dkr.ecr.eu-north-1.amazonaws.com/plant_diseases_detector:${{ github.sha }}

      - name: Restart Container
        run: |
          docker stop plant_diseases_detector || true
          docker rm plant_diseases_detector || true

          docker run -d \
            --name plant_diseases_detector \
            --restart always \
            -p 80:8000 \
            547619294594.dkr.ecr.eu-north-1.amazonaws.com/plant_diseases_detector:${{ github.sha }}